#!/bin/bash
# for linux

rm -f kill.txt
rm -f *.class
filename=${1%%.*}
args=$(echo $* | cut -d\  -f 2-)
if [ "$filename.java" == "$args" ] 
    then args=""
fi

javac -Xlint:all -Xmaxerrs 5 -cp .:lib/* $filename.java

if [ $? -eq 0 ]; then
    echo Compiled.
    java -cp .:lib/* $filename $args
fi

rm -f *.class
